# Generated by Django 3.0.6 on 2020-06-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200603_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
